# Generated by Django 3.1.3 on 2022-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=65, unique=True, verbose_name='Nombre de la Tarea'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('u', 'Tareas no iniciadas'), ('o', 'En Curso'), ('f', 'Finalizada')], max_length=1, verbose_name='Estado de la Tarea'),
        ),
    ]
